Examples- new pr
RoboticsBrno/ArduinoLearningKitStarter-library pull request #18
Opened 2019-04-15 18:51 UTC by TomasRoj

Okay, updated something. If it will not work lets ignore it. I am not good at this. Maybe it would be best dont do anything...

2019-04-15 19:04 UTC, TomasRoj commented
Only error I see that it doesn't recognize piezo1 from you library. Is it all capital letters?

2019-04-15 19:09 UTC, JarekParal commented
Please read the [documentation](https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library#piezo). Yes, it must be all capital letters. You can also see that in [source code](https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/blob/master/src/ALKS.h).

2019-04-15 19:14 UTC, TomasRoj commented
So if it will be capital letters will be everything okay?

2019-04-15 19:15 UTC, TomasRoj commented
I mean whole pull request

2019-04-15 19:26 UTC, TomasRoj commented
Updated now. It still doesn't work 😔

2019-04-15 19:58 UTC, bsaid commented
> Updated now. It still doesn't work

What exactly does not work? I have successfully compiled "buzzerSongs_Pirates" code for Arduino Nano and Uno. I actually don't have real hardware to test it.

2019-04-15 20:10 UTC, JarekParal commented
[The Travis.ci failed](https://travis-ci.org/RoboticsBrno/ArduinoLearningKitStarter-library/builds/520441023#L647). This is probably a problem with ESP32 and missing function tone().

2019-04-15 20:22 UTC, bsaid commented
> [The Travis.ci failed](https://travis-ci.org/RoboticsBrno/ArduinoLearningKitStarter-library/builds/520441023#L647). This is probably a problem with ESP32 and missing function tone().

I see, I suppose that @TomasRoj creates the examples on Arduino, not on ESP32. Am I true? If something is not working on Arduino, I would like to know about it. We can solve the ESP32 incompatibility later.

2019-04-15 20:39 UTC, JarekParal commented
Ok, we can have some examples just for Uno/Nano. But then somebody must solve this exeption in Travis.ci, because we want/need the CI.

Or there is another way with `#ifdef ESP32`  and use the `ledcWriteTone()` function which has ESP32: https://techtutorialsx.com/2017/07/01/esp32-arduino-controlling-a-buzzer-with-pwm/

Or there is also this issue: https://github.com/RoboticsBrno/ToneAC/issues/1

2019-04-16 05:19 UTC, TomasRoj commented
Okay. So everything on my side is OK?

2019-04-16 05:20 UTC, TomasRoj commented
I can write what @JarekParal said

2019-04-16 12:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RoboticsBrno/ArduinoLearningKitStarter-library?pullRequest=18) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RoboticsBrno/ArduinoLearningKitStarter-library?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RoboticsBrno/ArduinoLearningKitStarter-library?pullRequest=18) it.</sub>

2019-04-16 13:05 UTC, TomasRoj commented
Guys Problem is in Travis. I tried **Normal** code for uno/nano and it works on my wemos d1 too. there must be problem with travis ci tests.

2019-04-16 13:14 UTC, TomasRoj commented
guys, whole travis ci test is wrong. Even the only one example (pwmLed) what I left doesnt work on esp. It works on my board at home.

2019-04-16 13:51 UTC, JarekParal commented
No, the problem is with ESP32 which hasn't got support for standard function `analogWrite()` (which is available on Uno/Nano and probably also on ESP8266). This is the same problem as with the library ToneAc. Please read more about that and try to find some solution.

Posible sources of informations:
- https://techtutorialsx.com/2017/07/01/esp32-arduino-controlling-a-buzzer-with-pwm/
- https://github.com/espressif/arduino-esp32/issues/4

2019-04-16 13:57 UTC, TomasRoj commented
I already tried it. But when I did exception for esp travis ignored.

2019-04-16 14:08 UTC, TomasRoj commented
I dont know.. Why it can be only on uno/nano?

2019-04-16 14:15 UTC, TomasRoj commented
Still same problem even after I changed thngs you said: /home/travis/build/RoboticsBrno/ArduinoLearningKitStarter-library/examples/pwmLed/pwmLed.ino:1:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
 #import <ALKS.h>
  ^
pwmLed:15: error: conflicting declaration 'const int ledPin'
 const int ledPin = 16;  // 16 corresponds to GPIO16
           ^
/home/travis/build/RoboticsBrno/ArduinoLearningKitStarter-library/examples/pwmLed/pwmLed.ino:6:5: note: previous declaration as 'int ledPin'
 int ledPin = 8;     
     ^
/home/travis/build/RoboticsBrno/ArduinoLearningKitStarter-library/examples/pwmLed/pwmLed.ino: In function 'void setup()':
pwmLed:18: error: 'ledcSetup' was not declared in this scope
   ledcSetup(ledChannel, freq, resolution);
                                         ^
pwmLed:21: error: 'ledcAttachPin' was not declared in this scope
   ledcAttachPin(ledPin, ledChannel);

2019-04-16 14:31 UTC, JarekParal commented
Why you don't try firstly compilation of the code locally on your PC with setting for Una/Nano and then for ESP32 ([how to add esp32 to Arduino IDE](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md)) and fix all the error which you get? Or you can one again read the message from travis and fix the bugs:

> /home/travis/build/RoboticsBrno/ArduinoLearningKitStarter-library/examples/pwmLed/pwmLed.ino:1:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
#import <ALKS.h>
^
pwmLed:15: error: conflicting declaration 'const int ledPin'
const int ledPin = 16; // 16 corresponds to GPIO16
^
/home/travis/build/RoboticsBrno/ArduinoLearningKitStarter-library/examples/pwmLed/pwmLed.ino:6:5: note: previous declaration as 'int ledPin'
int ledPin = 8;

+ one hint: 
ledcSetup() and ledcAttachPin() are function available only for ESP32

2019-04-16 14:34 UTC, TomasRoj commented
I tought we are developing together to help beginners with arduino not playing az-quiz

2019-04-16 14:36 UTC, JarekParal commented
No, we are trying to help you learn new thing and became a better programmer ;).

2019-04-16 14:43 UTC, TomasRoj commented
IDK. It shows me same bug: error: 'ledcSetup' was not declared in this scope. Am i missing some library or something?

2019-04-16 14:50 UTC, JarekParal commented
Let's think. For which MCU you build the project? Which MCU has available `ledcSetup()` function?

2019-04-16 14:54 UTC, TomasRoj commented
for esp32

2019-04-16 15:40 UTC, JarekParal commented
Which ESP32 board you select in the Arduino IDE?

2019-04-16 17:31 UTC, cleveHEX requested changes
Look at this...

2019-04-16 17:31 UTC, CornyjK commented on examples/pwmLed/pwmLed.ino
> +const int ledPin = 16;  // 16 corresponds to GPIO16
Duplicate definition of existing variable can't be `const`

2019-04-16 17:31 UTC, CornyjK commented on examples/pwmLed/pwmLed.ino
> +int ledPin = 8;
This

2019-04-16 17:33 UTC, JarekParal commented
There is advice, how to fix the problem with ESP32 compilation.
```c
  #if defined(ESP32)
    ledcSetup(ledChannel, freq, resolution);
    
    // attach the channel to the GPIO to be controlled
    ledcAttachPin(ledPin, ledChannel);
  #endif
```

2019-04-16 20:35 UTC, CornyjK commented
> 
> 
> Still same problem even after I changed thngs you said: /home/travis/build/RoboticsBrno/ArduinoLearningKitStarter-library/examples/pwmLed/pwmLed.ino:1:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
> #import <ALKS.h>
> ^
> pwmLed:15: error: conflicting declaration 'const int ledPin'
> const int ledPin = 16; // 16 corresponds to GPIO16
> ^
> /home/travis/build/RoboticsBrno/ArduinoLearningKitStarter-library/examples/pwmLed/pwmLed.ino:6:5: note: previous declaration as 'int ledPin'
> int ledPin = 8;
> ^
> /home/travis/build/RoboticsBrno/ArduinoLearningKitStarter-library/examples/pwmLed/pwmLed.ino: In function 'void setup()':
> pwmLed:18: error: 'ledcSetup' was not declared in this scope
> ledcSetup(ledChannel, freq, resolution);
> ^
> pwmLed:21: error: 'ledcAttachPin' was not declared in this scope
> ledcAttachPin(ledPin, ledChannel);

Read my commits on #16

2019-04-17 05:49 UTC, TomasRoj commented
Thanks for help, I will look at that in the afternoon

2019-04-17 16:21 UTC, TomasRoj commented
@JarekParal seems like your code is wrong. I tried it and travis shows me error that #endif cannot be used without #if even it is there,

2019-04-19 20:49 UTC, bsaid commented
@TomasRoj I have reviewed your examples and modified them to work on both ESP32 and Arduino. I tested the modified code only on ESP32. If you are satisfied with the modification, you can commit it to your code and your pull request will be probably accepted.
I know, there is a complication with the code incompatibility between ESP32 and Atmel based Arduino. We will maybe separate examples for ESP32 and for Arduino. There are other reasons to do so, for example, WiFi on the ESP32.

2019-04-20 07:26 UTC, TomasRoj commented
Now I added files you created. It should work now

2019-04-20 07:28 UTC, TomasRoj commented
So no it doesn't work still. It says that analog write function was not declared...

2019-04-20 07:32 UTC, CornyjK commented
You seem like you have no idea what are you actually doing, you still have 2 examples in one folder, I'll fix it myself.

2019-04-20 07:40 UTC, TomasRoj commented
No it has that same problem with analog write function

2019-04-20 07:41 UTC, CornyjK commented
> 
> 
> No it has that same problem with analog write function

![image](https://user-images.githubusercontent.com/9021297/56454417-7734e700-6350-11e9-8ef6-393aafbf4d21.png)
it passed build on esp32, I will have to test it on real HW, though.

2019-04-20 07:44 UTC, TomasRoj commented
Yes but no PWM Led example

2019-04-20 08:41 UTC, CornyjK commented
@JarekParal 
someone made temporary esp32 tone library, you can check it [here](https://github.com/lbernstone/Tone).

2019-04-20 08:44 UTC, TomasRoj commented
@bsaid said that it's working on real esp32 both examples. We can merge

2019-04-20 08:46 UTC, CornyjK commented
> 
> 
> @bsaid said that it's working on real esp32 both examples. We can merge

No:
- It does not build, thus it can't work on esp32.
- It does not meet code quality standard at the moment.

2019-04-20 08:51 UTC, TomasRoj commented
Then look at what he wrote and consult it with him I did maximum

2019-04-20 10:05 UTC, bsaid commented
@TomasRoj The CI does not work, because in file pwmLed.ino at line 38 is "#endif", but should be "#else". The code below line 38 can run only on Arduino, but with wrong "#endif" line it run on both platforms.

2019-04-20 10:27 UTC, CornyjK commented
Anyways, I don't like such things being in examples, it is too hard to understand for ALKS end users (people with no knowledge). Examples should be easy to understand for anyone, without complex blobs. I will may implement HAL of `analogWrite` and `tone` soon to library (#20, #21).

2019-04-20 10:32 UTC, bsaid commented
> Anyways, I don't like such things being in examples, it is too hard to understand for ALKS end users (people with no knowledge). Examples should be easy to understand for anyone, without complex blobs. I will may implement HAL of `analogWrite` and `tone` soon to library (#20, #21).

@CornyjK I fully agree with you. But please, solve this PR first, and then we can improve the examples to be easier for beginners.

2019-04-20 10:55 UTC, CornyjK commented
It's still unclear where have you stolen the code, I can't merge any code without proper credits anyways.

2019-04-20 11:09 UTC, bsaid commented
I have updated the pwmLed.ino in my test branch: https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/tree/ExamplesTestBasedOnTomasRoj/examples/pwmLed

Sorry, I pushed the changes previously only for Pirates example.

2019-04-20 11:12 UTC, bsaid commented
@TomasRoj So, now my commit 6e152da91cef53987bab45438c515ac9f29d62e8 is accepted by the CI. Sorry for this.

2019-04-20 16:54 UTC, TomasRoj commented
So finsihed pr?

2019-04-20 17:39 UTC, CornyjK commented
> 
> 
> So finsihed pr?

You did not met all requirements which I stated in this or #16 PR.

2019-04-20 17:40 UTC, CornyjK commented
> 
> 
> @TomasRoj So, now my commit [6e152da](https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/commit/6e152da91cef53987bab45438c515ac9f29d62e8) is accepted by the CI. Sorry for this.

You can directly edit his code, so he does not need to recommit your changes.

2019-04-20 17:41 UTC, CornyjK commented
The LED PWM is already done in #23, so it is not needed anyways.

2019-04-20 19:48 UTC, TomasRoj commented
Maybe, in the time when we will discuss this pr I can help you with documentation or something similar to that. What do you think? Is something in work-in-progress ?

2019-04-27 08:37 UTC, closed without merging